### ISSUE TITLE
Possible issue with xref keyref processing

### ISSUE THREAD

**Issue by shaneataylor** [oxygenxml/dita-relaxng-defaults#2]
I can't compare apples to apples since without the plugin I can't build RNG-based topics at all, but I'm seeing errors resulting from `<xref keyref="key"/>` in topics. 

* The key is defined (and at any rate, if it weren't, that's an info message).
* The key points to a topic that builds and is listed in the logs.
* Using DITA-OT 2.3.1.

Error messages resemble:
```
Processing build/temp/lo-authoring-help/submission-based-assessments.dita
Recoverable error on line 576 of topicpullImpl.xsl:
  FODC0002: java.io.FileNotFoundException:
  build/deps/DITA-OT2.3.1/xsl/preprocess/find-add.dita
  (No such file or directory)
file:archive.dita:8:35: [DOTX031E][ERROR]: The file find-add.dita is not available to resolve link information. 
Recoverable error on line 654 of topicpullImpl.xsl:
  FODC0002: java.io.FileNotFoundException:
  build/deps/DITA-OT2.3.1/xsl/preprocess/find-add.dita
  (No such file or directory)
Recoverable error on line 1820 of topicpullImpl.xsl:
  FODC0002: java.io.FileNotFoundException:
  build/deps/DITA-OT2.3.1/xsl/preprocess/find-add.dita
  (No such file or directory)
```

I *think* the problem is that the processing is looking for the temp file in the wrong path (`build/deps/DITA-OT2.3.1/xsl/preprocess/find-add.dita`).

The error happens when the plugin is installed whether the source or target topics (or maps) are DTD-based or RNG-based.

**Comment by shaneataylor** [comment]
Oddly, this doesn't happen for _all_ xrefs using keyref, and I haven't yet been able to identify what's different about the ones that work.

**Comment by shaneataylor** [comment]
This is a bug (feature?) in the DITA-OT, and happens when a keyref points to a topic that itself has a keyref in its short description.

**Comment by shaneataylor** [comment]
Opened DITA-OT issue https://github.com/dita-ot/dita-ot/issues/2708

**Comment by raducoravu** [comment]
So basically if the same problem occurs with DTD-based maps and topics then it's a DITA OT issue.
