### ISSUE TITLE
Fix installation instructions in README.md

### ISSUE THREAD

**Issue by stefan-jung** [oxygenxml/dita-relaxng-defaults#3]
Hi @raducoravu,

could you please fix the installation instructions in the README?

```
copy the folder "com.oxygenxml.rng.defaults" to the plugins folder and run the integrator
```

There's no `com.oxygenxml.rng.defaults` folder anymore in this plugin. If you like, I'll spawn a PR.

**Comment by raducoravu** [comment]
Thanks @xephon2 , I did.
