### ISSUE TITLE
Plugin is not compatible with DITA-OT 3.x

### ISSUE THREAD

**Issue by stefan-jung** [oxygenxml/dita-relaxng-defaults#4]
Hi,

I'm trying to replace my DITA-OT 2.5.4 with DITA-OT 3.1. We are using RelaxNG based DITA. The DITA-OT fails with:

```
Error: Failed to run pipeline: [DOTJ022F][FATAL]
Failed to parse the input file 'file:/C:/Users/x/DITA/test.ditamap'
because all of its content has been filtered out.
This will happen if the input file has filter conditions on the root element,
and a ditaval excludes all content based on those conditions.
```

Publishing DTD based maps and topics works with DITA-OT 3.x, so it is probably related to this plugin.

The README.md does not mention DITA-OT 3.x. Is a DITA-OT 3.x support planned?

**Comment by raducoravu** [comment]
Downloaded a DITA OT 3.1, copied this plugin to its "plugins" folder, run the integrator, created a RNG-based DITA Map having a reference to a RNG-based topic, run from the command line something like:

                dita -i D:\path\to\myMap.ditamap -f html5 -v

and it works for me. 

Indeed the error you posted seems to indicate the reference from the map to the schema is not taken into account.
Maybe you forgot to add other specific specialization plugins to the DITA OT 3.1 plugins folder... or you have some kind of custom script which runs the DITA OT with a slightly changed class path, without using the "dita" script.

**Comment by chrispitude** [comment]
I seem to be running into this too. My Relax NG DITA topic transforms fine if the xml-model uses a filesystem reference:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="/home/chrispy/dita-ot/plugins/com.mine.docshell/doctypes/topic/rng/basetopic.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>
<topic id="testtopic123">
    <title>Topic Title</title>
    <body><p>This is a test.</p></body>
</topic>
```

but it fails with the failure message if a URI reference is used:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="com:mine:docshell:basetopic.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>
<topic id="testtopic123">
    <title>Topic Title</title>
    <body><p>This is a test.</p></body>
</topic>
```

If I install my document-type shell into Oxygen, the URI-based reference works properly (and I can confirm that by adding a typo to cause Oxygen to fail to resolve the catalog reference, then fix it to re-resolve it). It is only when I use DITA-OT with the relax-ng-defaults plugin that the URI reference to my document-type shell does not resolve.

xephon2, I'm not ruling out user error here too. Did you figure something out that makes this work? Or do your findings match mine?

Radu, if relax-ng-defaults uses jing/trang, it's possible that [this Jing issue](https://github.com/relaxng/jing-trang/issues/200) is causing this problem.

**Comment by raducoravu** [comment]
@chrispitude On what operating system are you working? Are you publishing from the command line or from Oxygen?
If you give me (not necessarily via this thread, you can email our Oxygen XML tech support address directly) a precise set of steps (download dita ot, install RNG plugin, install RNG specialization integrate, what command line you are calling) + sample DITA project + specialization plugin I could try to reproduce the problem on my side and look into it.

**Comment by stefan-jung** [comment]
@chrispitude, I kept using the 2.5.4 toolkit. To be honest, I cannot remember, if I fixed this error. But I used the OT 3.x with RNG in other projects, so it was probably my fault, probably a specialization bug.

**Comment by chrispitude** [comment]
> @chrispitude, I kept using the 2.5.4 toolkit. To be honest, I cannot remember, if I fixed this error. But I used the OT 3.x with RNG in other projects, so it was probably my fault, probably a specialization bug.

This ended up being user error on my part. Radu found that I needed both &lt;uri/> **and** &lt;system/> definitions in my docshell's catalog.xml file for the Relax NG code to resolve the catalog entries:

```
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <uri name="com:test:docshell:basetopic.rnc" uri="rnc/basetopic.rnc"/>
  <system systemId="com:test:docshell:basetopic.rnc" uri="rnc/basetopic.rnc"/>
</catalog>
```

**Comment by raducoravu** [comment]
@chrispitude I also updated the readme of the plugin with this information which was not stated anywhere.
